POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imtrb3NvbGEiLCJpZCI6IjY2NjJjMjAxNGM5M2JjNzc5MTcxZDg3MyIsImlhdCI6MTcxNzc0ODI5NiwiZXhwIjoxNzE3NzUxODk2fQ.jktdkMRnbZrb_hZgj6hTA6XbGW1ANkkiMmu0cqjERas

{
    
   "title": "Salatut elämät analyysi",
   "author": "El Maestro of Salkkarit",
    "likes": 82
}
